services:
  elliptical:
    restart: always
    build:
      context: ./
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USER=elliptical
      - DB_PASS=yourpassword
      - DB_NAME=elliptical

  mariadb:
    restart: always
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=elliptical
      - MYSQL_USER=elliptical
      - MYSQL_PASSWORD=yourpassword
    volumes:
      - ./mysql:/var/lib/mysql
